### ISSUE TITLE
Not Enabling Correctly and needs reload after server restart

### ISSUE THREAD

**Issue by Waffl3Development** [Team-Inceptus/Novaconomy#33]
### Bug Type

Other Unexpected Behavior

### Minecraft Version

1.19.2

### Description

Whenever I restart my server I need to use something like plugman to reload the plugin again as all the commands return with unknown or incomplete command see below for error
![image](https://user-images.githubusercontent.com/70445191/193986146-ebc1153a-5582-488f-80e7-f8e7ee9d761c.png)
![image](https://user-images.githubusercontent.com/70445191/193986283-6252fd15-ddff-4bf6-8985-648e480cb262.png)

After Reloading the plugin, Treasury throws errors as well (not sure if its on treasurys end or this plugin)
[2022-10-05-3.log](https://github.com/Team-Inceptus/Novaconomy/files/9712946/2022-10-05-3.log)
The error can be seen in my log file

### Steps to Reproduce

drag and drop Novaconomy into the plugins folder with Treasury on 1.19.2 Paper on Linux(not sure if specific to linux)
restart server and log in
test any command and error will appear

if you have plugman and choose to reload Novaconomy shortly after Treasury throws an error

### Expected Behavior

Novaconomy commands should work correctly right off the bat

### Actual Behavior

they do not work and the plugin needs to be reloaded with something like plugman but doing so causes an error with treasury

### Additional Info

I am using the latest version of paper along with waterfall not sure if that would cause any other issues

**Comment by GamerCoder215** [comment]
I'm not entire sure what the hell the plugin is doing with treasury...
If you have any error logs for when plugman or another utility restarts/reloads the plugin, please provide those.

I'll try to look into the error more, but this log is just confusing😓 (not your fault)

**Comment by GamerCoder215** [comment]
@Waffl3Development if you could provide additional logs for when you restart your plugin (if any) pertaining to when Novaconomy loads its commands, otherwise I have to close this issue.

**Comment by Waffl3Development** [comment]
@GamerCoder215 unfortunately there isnt any other logs if i do it with plugman it only provides the errors you saw and if I do not use the plugman command it does not show any errors, I am going to quickly restart without plugman installed to see if it makes a difference and I will upload that log

**Comment by Waffl3Development** [comment]
@GamerCoder215 I tried to start it up with plugmanX not installed and no change still cannot use commands I took a look in the latest log but I do not see any specific errors I will also note that treasury does not register novaconomy as an economy with this issue as well
[latest.log](https://github.com/Team-Inceptus/Novaconomy/files/9737696/latest.log)
![image](https://user-images.githubusercontent.com/70445191/194669505-c595af91-de78-4dd0-ac76-6abb76cf3ccd.png)

**Comment by GamerCoder215** [comment]
Tracked on [Treasury #209](https://github.com/lokka30/Treasury/issues/209). If you can, please output your Treasury versions.

@Waffl3Development I believe you mentioned that Novaconomy commands weren't working, can you elaborate on that please?

**Comment by Waffl3Development** [comment]
@GamerCoder215 I am using Treasury v1.2.0 Release (which I think is the latest) 
![image](https://user-images.githubusercontent.com/70445191/194671385-a00ddde3-30a1-44fb-a7ef-af993b9e374f.png)
the problem with the commands is that none of them seem to work and give me the unknown or incomplete command no matter which command I use

**Comment by GamerCoder215** [comment]
You said that they don't provide an error? If so, please attach it.
The earlier log you attached indicates that the command did work and go through.

**Comment by Waffl3Development** [comment]
They do not provide an error the log shows it going through but I just get the unknown or incomplete command error thing

**Comment by GamerCoder215** [comment]
> They do not provide an error the log shows it going through but I just get the unknown or incomplete command error thing

Have you tried fully shutting off and turning on the server (not just a /restart)?

It might also be an issue with brigadier, try seeing if commands run in the console.

**Comment by Waffl3Development** [comment]
to restart the server I do /stop then start it up again (never got around to really setting up /restart), but good news the commands work in the console, not sure why but treasury has novaconomy crossed out
![image](https://user-images.githubusercontent.com/70445191/194675704-de040029-9405-49a8-8f2a-30ea8e6f585d.png)

**Comment by GamerCoder215** [comment]
Brigadier is weird...
I'll take a look at why a provider would be crossed.

As with the player thing, try rejoining. The reason why it works with the console and not players is that sometimes brigadier loads after players have joined (I assume it's a bug, but I'll look into more details about it later), meaning that commands aren't registered.

**Comment by Waffl3Development** [comment]
Rejoining does not seem to work would you happen to know if bungeecord/waterfall cause issues either with novaconomy or brigadier?

**Comment by Waffl3Development** [comment]
okay update i figured out why treasury crossed out novaconomy I had treasury (as well on the servers) in bungee but novaconomy only on one server, which wasnt needed so you dont need to look into that

**Comment by GamerCoder215** [comment]
Couldn't find anything relating to bungeecord or waterfall having issues with brigadier.

I'll have to look into it further, but I couldn't confirm it working on my MC Version.

**Comment by Waffl3Development** [comment]
wait so it did work for you or did not?

**Comment by GamerCoder215** [comment]
Works fine for me.
![image](https://user-images.githubusercontent.com/54124162/194680512-fd74839a-3ae2-40e0-ba14-d9788e4671a1.png)

**Comment by Waffl3Development** [comment]
weird

**Comment by GamerCoder215** [comment]
> weird

Does this happen for any other plugin that uses brigadier commands (I think LuckPerms has it)? Or is it just Novaconomy?

**Comment by Waffl3Development** [comment]
just novaconomy as far as I can tell luckperms works perfectly from what I can see

**Comment by GamerCoder215** [comment]
Will report to the command framework people. Hopefully, I can provide details within the next couple of hours. 
Sorry you're having issues with this.

**Comment by Waffl3Development** [comment]
its no problem I'm just super confused as to why its doing it haha

**Comment by GamerCoder215** [comment]
Not sure either.
As a temporary fix, you can disable brigadier in `functionality.yml` by setting `CommandVersion` to `1` (this will remove all of the fancy colorings and auto-checking, but the commands should work).

**Comment by Waffl3Development** [comment]
I tried to make a fresh server just to test and I got a new error, it still generates a folder with configs and stuff but if i boot it up again with the generated configs, i dont get the error in the log attached but i get my error in game
[latest.log](https://github.com/Team-Inceptus/Novaconomy/files/9738271/latest.log)

also when you tested earlier did you test on a linux system? (just trying to think of potential differences)

I will try out the functionality.yml thing and let you know

**Comment by GamerCoder215** [comment]
Fixed in [2d0160c](https://github.com/Team-Inceptus/Novaconomy/commit/2d0160c), which should be included in v1.6.2 (releasing either Sunday or Monday).

If you don't know how to compile the plugin with the fix, I have left instructions below.
(Do these on a home computer, then upload the building product to an online server host if need be)

<details>
  <summary>Compiling on an experimental branch</summary>


To build the latest experimental version, complete these steps:

1.) Install at least JDK 17 (if not already installed)
- You can check with `java --version` in your OS's terminal
- Should already be installed to operate any MC server, but make sure it is 17 or above
2.) Install Maven (if not already installed)
- You can check with `mvn -v` in your OS's terminal
3.) Install Git (if not already installed)
- You can check with `git --version` in your OS's terminal

**1** and **3** should be pre-installed on Linux and Mac, I think **2** may be installed on some Linux distros, but all 3 are definitely not pre-installed with Windows.

4.) Run: `git clone --branch ver/1.6 https://github.com/Team-Inceptus/Novaconomy.git` on any terminal application
- You can change `ver/1.6` to whatever version you need (i.e. `ver/1.4` is v1.4.1)
- Subversions are not available, branches will only have 2 numbers in them, containing the latest subversion (i.e. ver/1.4 is 1.4.1)
5.) Move into cloned directory (should be directory containing a pom.xml file)
6.) Run `mvn clean install`, wait for "Build Successful" screen
7.) Move into `plugin` folder, then `target` folder
8.) `Novaconomy-(BRANCH VERSION)-SNAPSHOT.jar` is the full plugin jar, use that as your plugin
- Example: `ver/1.5` will produce `Novaconomy-1.5.0-SNAPSHOT.jar`
- `ver/1.6` will produce `Novaconomy-1.6.2-SNAPSHOT.jar`, the latest experimental version
</details>

Please ask any questions about the process here (Feel free to research the commands/applications if you want).

**Comment by Waffl3Development** [comment]
well i updated to plugin version 1.6.2 which fixed the loop issue but the command issue still remains, but disabling brigadier in the functionality.yml by setting CommandVersion to 1 seems to work

Thanks for all of the help

**Comment by GamerCoder215** [comment]
> well i updated to plugin version 1.6.2 which fixed the loop issue but the command issue still remains, but disabling brigadier in the functionality.yml by setting CommandVersion to 1 seems to work
> 
> Thanks for all of the help

I assume the server would be in offline mode?
I'll continue to do research for the brigadier issue for offline mode servers, but for now I will close this thread.
Thanks for the information!
